version: "3"
networks:
  crm:
    driver: bridge
services:
  web:
    restart: always
    build: ./
    image: myimage
    command:  uvicorn main:app --host 0.0.0.0 --reload 
    ports:
      - 8000:8000
    networks:
      - crm
 
  mysql:
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "~/.bnpj/data/mysql:/var/lib/mysql"
      - "./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: haddi
    networks:
      - crm

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
    networks:
      - crm


